# kafka-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka-manual
data:
  server.properties: |
    auto.create.topics.enable=true
    num.partitions=1
    default.replication.factor=1