# kafka-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: zookeeper.connect
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: advertised.listeners
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: listeners
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: broker.id
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: offsets.topic.replication.factor
            - name: KAFKA_LOG_FLUSH_INTERVAL_MESSAGES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: log.flush.interval.messages
            - name: KAFKA_LOG_RETENTION_HOURS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: log.retention.hours
            - name: KAFKA_LOG_SEGMENT_BYTES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: log.segment.bytes
          command:
            - sh
            - -c
            - |
              #!/bin/sh
              cp /opt/kafka/config/server.properties /tmp/server.properties
              echo "broker.id=${KAFKA_BROKER_ID}" >> /tmp/server.properties
              echo "listeners=${KAFKA_LISTENERS}" >> /tmp/server.properties
              echo "advertised.listeners=${KAFKA_ADVERTISED_LISTENERS}" >> /tmp/server.properties
              echo "zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}" >> /tmp/server.properties
              echo "log.dirs=${KAFKA_LOG_DIRS}" >> /tmp/server.properties
              echo "log.flush.interval.messages=${KAFKA_LOG_FLUSH_INTERVAL_MESSAGES}" >> /tmp/server.properties
              echo "log.retention.hours=${KAFKA_LOG_RETENTION_HOURS}" >> /tmp/server.properties
              echo "log.segment.bytes=${KAFKA_LOG_SEGMENT_BYTES}" >> /tmp/server.properties
              echo "offsets.topic.replication.factor=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}" >> /tmp/server.properties
              exec /opt/kafka/bin/kafka-server-start.sh /tmp/server.properties