apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: kafka-manual
spec:
  serviceName: "kafka-service"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command: ['sh', '-c', 'cp /etc/kafka/* /var/lib/kafka/config/ && cp /etc/kafka/log4j.properties /opt/kafka/config/ && chmod -R 777 /var/lib/kafka/config']
        volumeMounts:
        - name: config-volume
          mountPath: /etc/kafka
        - name: kafka-config
          mountPath: /var/lib/kafka/config
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: kafka-config
          mountPath: /opt/kafka/config
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service.kafka-manual.svc.cluster.local:9092
      volumes:
      - name: config-volume
        configMap:
          name: kafka-config-1
      - name: kafka-config
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: kafka-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
