# kafka-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LISTENERS
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_LOG_FLUSH_INTERVAL_MESSAGES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LOG_FLUSH_INTERVAL_MESSAGES
            - name: KAFKA_LOG_RETENTION_HOURS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LOG_RETENTION_HOURS
            - name: KAFKA_LOG_SEGMENT_BYTES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LOG_SEGMENT_BYTES