apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: kafka-manual
spec:
  serviceName: kafka-broker
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://$(POD_NAME).kafka-broker.kafka-manual.svc.cluster.local:9092"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_CFG_auto_create_topics_enable
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: kafka.properties
        volumeMounts:
        - name: kafka-config-volume
          mountPath: /etc/kafka/kafka.properties
          subPath: kafka.properties
          readOnly: true
        - name: kafka-logs
          mountPath: /kafka-logs
      volumes:
      - name: kafka-config-volume
        configMap:
          name: kafka-config
          items:
          - key: kafka.properties
            path: kafka.properties
  volumeClaimTemplates:
  - metadata:
      name: kafka-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi