apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka-manual
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka-broker
  type: ClusterIP
