apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: kafka-manual
spec:
  ports:
    - port: 9092
  clusterIP: None  # Headless service
  selector:
    app: kafka  # Pastikan ini sesuai dengan label pada pod Kafka Anda
