apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka-manual
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka-port
  selector:
    app: kafka-broker