apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
  namespace: dbz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
      - name: debezium
        image: debezium/connect:latest
        ports:
        - containerPort: 8083
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-broker-0.kafka-broker.kafka-manual.svc.cluster.local:9092,kafka-broker-1.kafka-broker.kafka-manual.svc.cluster.local:9092,kafka-broker-2.kafka-broker.kafka-manual.svc.cluster.local:9092"
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "my_connect_configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "my_connect_offsets"
        volumeMounts:
        - name: register-connector
          mountPath: /register
      volumes:
      - name: register-connector
        configMap:
          name: register-postgres
          items:
            - key: register-postgres.json
              path: register-postgres.json
