apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
  namespace: dbz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
      - name: debezium
        image: debezium/connect:latest
        ports:
        - containerPort: 8083
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-service.kafka-manual.svc.cluster.local:9092"
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "my_connect_configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "my_connect_offsets"
        volumeMounts:
        - name: register-connector
          mountPath: /register
      volumes:
      - name: register-connector
        configMap:
          name: register-postgres
          items:
            - key: register-postgres.json
              path: register-postgres.json

# kubectl exec -it debezium-5b7bd5b49b-q6nd4 -n dbz -- curl -X POST -H "Content-Type: application/json" --data @/register/register-postgres.json http://localhost:8083/connectors
# kubectl exec -it debezium-5b7bd5b49b-q6nd4 -n dbz -- curl http://localhost:8083/connectors/inventory-connector/status

# kubectl exec kafka-broker-0 -- ./bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic inventory.public.users --from-beginning --max-messages 10
