apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: appv1-ingress
spec:
  controller: konghq.com/ingress-controller
  rules:
  - host: coba-coba-aja.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: goapp-v2-helm-gov1
            port:
              number: 80
