apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress-v1
  namespace: argocd  # Pas
  annotations: 
    kubernetes.io/ingress.class: kong
spec:
  tls:
  - hosts:
    - blog.coba-coba-aja.website
    secretName: cloudflare-tls-blog
  rules:
  - host: blog.coba-coba-aja.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
