# values.yaml
alertmanager:
  enabled: true
server:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

prometheus:
  prometheusSpec:
    scrapeConfigs:
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-application-service-xporter.argocd.svc.cluster.local:9113']
# helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring -f tools/prometheus/values.yaml
# export POD_NAME=$(kubectl get pods --namespace monitoring -l "app.kubernetes.io/name=prometheus,app.kubernetes.io/instance=prometheus" -o jsonpath="{.items[0].metadata.name}")
# kubectl --namespace monitoring port-forward $POD_NAME 9090