apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goapp-v2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aryadiahmad4689/infra-test.git'
    targetRevision: 'master'  # Atau spesifikasikan versi chart yang diinginkan
    path: application/helm-gov1/ #ini adalah path tempat helm chart anda untun menjalankan aplikasi kalian
    helm:
      valueFiles:
        - "values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd  # Ganti dengan namespace target di kluster Anda
  syncPolicy:
    automated: {}
    

# kubectl apply -f tools/argocd/goappv1-argocd.yaml