apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goapp-v2
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr-safe-me-staging=asia-southeast2-docker.pkg.dev/ascendant-chain-336811/fazpass/safe-me-backend:latest
    argocd-image-updater.argoproj.io/gcr-safe-me-staging.update-strategy: digest
    argocd-image-updater.argoproj.io/gcr-safe-me-staging.ignore-tags: master, staging, dev
    # argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    # argocd-image-updater.argoproj.io/write-back-method: git:repocreds
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  project: default
  source:
    repoURL: 'https://github.com/aryadiahmad4689/infra-test.git'
    targetRevision: 'master'  # Atau spesifikasikan versi chart yang diinginkan
    path: application/helm-app2/ #ini adalah path tempat helm chart anda untun menjalankan aplikasi kalian
    helm:
      valueFiles:
        - "values.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging  # Ganti dengan namespace target di kluster Anda
  syncPolicy:
    automated: {}
    

# kubectl apply -f tools/argocd/goappv1-argocd.yaml