# values.yaml
replicaCount: 1

image:
  repository: nginx/nginx-prometheus-exporter
  tag: "0.9.0"  # Ganti dengan versi yang diinginkan
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9113

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics
  port: 9113
