apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: db
data:
  postgresql.conf: |
    listen_addresses = '*'
    wal_level = logical
    max_replication_slots = 4
    max_wal_senders = 4
    shared_buffers = 128MB
    log_line_prefix = '%m [%p] %q%u@%d '
    log_timezone = 'UTC'
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.UTF-8'
    lc_monetary = 'en_US.UTF-8'
    lc_numeric = 'en_US.UTF-8'
    lc_time = 'en_US.UTF-8'
    default_text_search_config = 'pg_catalog.english'
