apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appv1-ingress
spec:
  rules:
  - host: socials-market.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ServiceName
            port:
              number: 80