name: Deploy to GCR

on:
  push:
    branches:
      - master  # Atau branch yang Anda gunakan
env:
  REGISTRY: us.gcr.io
  REGISTRY_NAME: appv1
  PROJECT_ID: tetscloud
  SHA: ${GITHUB_SHA}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version tag
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - uses: RafikFarhad/push-to-gcr-github-action@v4.1
      with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY}}
          registry: ${{ env.REGISTRY }}
          project_id: ${{ env.PROJECT_ID }}
          image_name: ${{ env.REGISTRY_NAME }}
          dockerfile: ./golang_app/Dockerfile
          context: ./golang_app/
          image_tag: v1.0.1
